-- ===========================================================================
-- wispcord member page — Cloudflare Pages Functions schema
--
-- Paste this whole file into the Supabase SQL Editor and press Run. It is
-- idempotent: every statement is safe to run more than once, and it does not
-- touch the tables the admin/member bots already own.
--
-- Access model, in one paragraph. The browser holds the **anon** key (it is
-- baked into member.html), so the anon key must never be able to read anything
-- private. Every table below therefore has RLS enabled with **no anon policy at
-- all**: the Cloudflare Worker reads and writes them with
-- SUPABASE_SERVICE_KEY, which is a Pages secret and never reaches a browser.
-- The Worker is what enforces "this ticket is yours", using the signed session
-- cookie — so the rule is enforced in one place, not in a policy an attacker
-- could query around.
--
-- The two exceptions are the tables the page still fetches directly with the
-- anon key: `bot_status` (already readable, see wispbyte_schema.sql) and
-- `members` (already readable today). Nothing here changes those.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 1. ticket_queue — new tickets, exactly as wispbyte_schema.sql defines them
--    (recreated here so this file stands alone; if it already exists the body
--    is left alone and only the RLS policies are refreshed)
-- ---------------------------------------------------------------------------
create table if not exists public.ticket_queue (
  id              bigint generated by default as identity primary key,
  ticket_id       text,
  category        text,
  category_label  text,
  subject         text,
  body            text,
  contact         text,
  priority        text default 'normal',
  answers         jsonb default '{}'::jsonb,
  attachments     jsonb default '[]'::jsonb,
  discord_user_id text,
  discord_tag     text,
  anonymous       boolean default false,
  status          text default 'queued',
  created_at      timestamptz default now(),
  processed_at    timestamptz
);

-- Columns added after the first release are patched in one at a time, because
-- `create table if not exists` will not add them to an existing table.
alter table public.ticket_queue add column if not exists category_label text;
alter table public.ticket_queue add column if not exists contact text;
alter table public.ticket_queue add column if not exists priority text default 'normal';

create index if not exists ticket_queue_unprocessed_idx
  on public.ticket_queue (processed_at) where processed_at is null;

alter table public.ticket_queue enable row level security;

-- No anon policy: the Worker uses the service key. Dropping the older
-- browser-insert policy is deliberate — the Worker is the only writer now, so
-- the `discord_user_id` on a ticket is always the id it verified.
drop policy if exists "anon can insert tickets" on public.ticket_queue;
drop policy if exists "service full access ticket_queue" on public.ticket_queue;
create policy "service full access ticket_queue"
  on public.ticket_queue
  for all
  to service_role
  using (true)
  with check (true);

-- ---------------------------------------------------------------------------
-- 2. ticket_reply_queue — member replies to an existing ticket
-- ---------------------------------------------------------------------------
create table if not exists public.ticket_reply_queue (
  id              bigint generated by default as identity primary key,
  ticket_id       text not null,
  body            text,
  attachments     jsonb default '[]'::jsonb,
  discord_user_id text,
  discord_tag     text,
  status          text default 'queued',
  created_at      timestamptz default now(),
  processed_at    timestamptz
);

create index if not exists ticket_reply_queue_unprocessed_idx
  on public.ticket_reply_queue (processed_at) where processed_at is null;

create index if not exists ticket_reply_queue_ticket_idx
  on public.ticket_reply_queue (ticket_id);

alter table public.ticket_reply_queue enable row level security;

drop policy if exists "anon can insert replies" on public.ticket_reply_queue;
drop policy if exists "service full access ticket_reply_queue" on public.ticket_reply_queue;
create policy "service full access ticket_reply_queue"
  on public.ticket_reply_queue
  for all
  to service_role
  using (true)
  with check (true);

-- ---------------------------------------------------------------------------
-- 3. member_tickets — the member-visible index of their own tickets
--
--    Rows are written by the Worker when a ticket is opened and kept in step
--    by the admin bot: when staff reply it appends to `replies`, when it closes
--    the ticket it sets `status = 'closed'`.
-- ---------------------------------------------------------------------------
create table if not exists public.member_tickets (
  id              bigint generated by default as identity primary key,
  ticket_id       text not null unique,
  category        text,
  category_label  text,
  subject         text,
  contact         text,
  priority        text default 'normal',
  answers         jsonb default '{}'::jsonb,
  attachments     jsonb default '[]'::jsonb,
  replies         jsonb default '[]'::jsonb,
  discord_user_id text not null,
  discord_tag     text,
  status          text default 'open',
  created_at      timestamptz default now(),
  updated_at      timestamptz default now(),
  closed_at       timestamptz
);

create index if not exists member_tickets_user_idx
  on public.member_tickets (discord_user_id, created_at desc);

alter table public.member_tickets enable row level security;

drop policy if exists "service full access member_tickets" on public.member_tickets;
create policy "service full access member_tickets"
  on public.member_tickets
  for all
  to service_role
  using (true)
  with check (true);

-- ---------------------------------------------------------------------------
-- 3b. bot_status — column added after the first release
--     The member bot sends uptime_seconds on every heartbeat. ALTER, not
--     create: the table already exists on a live project.
-- ---------------------------------------------------------------------------
alter table public.bot_status add column if not exists uptime_seconds integer default 0;

-- ---------------------------------------------------------------------------
-- 4. member_profiles — the personal touches on the member page
--    (bio, name colour, font, effect, nickname preference)
-- ---------------------------------------------------------------------------
create table if not exists public.member_profiles (
  user_id       text primary key,
  bio           text,
  show_nickname boolean default true,
  name_color    text,
  name_font     text,
  name_effect   text,
  updated_at    timestamptz default now()
);

alter table public.member_profiles enable row level security;

drop policy if exists "service full access member_profiles" on public.member_profiles;
create policy "service full access member_profiles"
  on public.member_profiles
  for all
  to service_role
  using (true)
  with check (true);

-- ---------------------------------------------------------------------------
-- 5. staff_titles — the badge rules the member page applies to names
--
--    Shape per row:
--      roles    jsonb  ["<role id>", ...]      matched against the member's roles
--      keywords jsonb  ["moderator", ...]      matched against role names
--      style    jsonb  the admin bot's style object
--                      (effect, colors, font, weight, size, spacing, italic,
--                       uppercase, fill, radius, pad_x, pad_y, border, glow)
--    Priority decides the winner when more than one rule matches.
-- ---------------------------------------------------------------------------
create table if not exists public.staff_titles (
  id         text primary key,
  label      text not null,
  prefix     text,
  suffix     text,
  priority   integer default 0,
  roles      jsonb default '[]'::jsonb,
  keywords   jsonb default '[]'::jsonb,
  style      jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

alter table public.staff_titles enable row level security;

drop policy if exists "service full access staff_titles" on public.staff_titles;
create policy "service full access staff_titles"
  on public.staff_titles
  for all
  to service_role
  using (true)
  with check (true);

-- ---------------------------------------------------------------------------
-- 6. mod_cases — the caller's own moderation history
--
--    The admin bot writes one row per action. `user_id` is the punished
--    member's Discord id; the bot keeps its service-key access.
-- ---------------------------------------------------------------------------
create table if not exists public.mod_cases (
  id         text primary key,
  user_id    text not null,
  action     text,
  reason     text,
  moderator  text,
  status     text default 'active',
  timestamp  timestamptz default now()
);

create index if not exists mod_cases_user_idx
  on public.mod_cases (user_id, timestamp desc);

alter table public.mod_cases enable row level security;

drop policy if exists "service full access mod_cases" on public.mod_cases;
create policy "service full access mod_cases"
  on public.mod_cases
  for all
  to service_role
  using (true)
  with check (true);

-- ---------------------------------------------------------------------------
-- 6b. economy — a READ-ONLY mirror of the member bot's JSON balances
--
--     The bot keeps economy.json as its source of truth and republishes every
--     record here once a minute, so the member site can show coins and levels
--     without reaching into the bot's disk.
--
--     anon may SELECT this: it is public game data, the same numbers every
--     member can already see with `>baltop`. There is deliberately no anon
--     write policy — only the bot (service key) may update it.
-- ---------------------------------------------------------------------------
create table if not exists public.economy (
  user_id    text primary key,
  balance    bigint default 0,
  bank       bigint default 0,
  xp         integer default 0,
  level      integer default 1,
  wins       integer default 0,
  losses     integer default 0,
  streak     integer default 0,
  updated_at timestamptz default now()
);

alter table public.economy enable row level security;

drop policy if exists "anon can read economy" on public.economy;
create policy "anon can read economy"
  on public.economy
  for select
  to anon
  using (true);

drop policy if exists "service full access economy" on public.economy;
create policy "service full access economy"
  on public.economy
  for all
  to service_role
  using (true)
  with check (true);

-- ---------------------------------------------------------------------------
-- 7. Storage bucket for ticket attachments
--    Public to read (a ticket reply has to render the image), writable only
--    with the service key the Worker holds.
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('ticket-attachments', 'ticket-attachments', true)
on conflict (id) do nothing;

drop policy if exists "service can write ticket attachments" on storage.objects;
create policy "service can write ticket attachments"
  on storage.objects
  for insert
  to service_role
  with check (bucket_id = 'ticket-attachments');

drop policy if exists "anyone can read ticket attachments" on storage.objects;
create policy "anyone can read ticket attachments"
  on storage.objects
  for select
  to anon, authenticated
  using (bucket_id = 'ticket-attachments');

-- ---------------------------------------------------------------------------
-- 8. Sanity check — what the Worker will see
-- ---------------------------------------------------------------------------
-- select id, updated_at, guild_count, member_count, latency_ms from public.bot_status;
-- select count(*) from public.member_tickets;
-- select id, label, priority from public.staff_titles order by priority desc;
